# Generated by Django 5.1.4 on 2024-12-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitem',
            old_name='save',
            new_name='save_user',
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
