# Generated by Django 5.1.4 on 2024-12-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_rename_save_saveitem_save_user_alter_post_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_commenter',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='user',
            new_name='user_comment_liker',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_poster',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='user',
            new_name='user_post_liker',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='user',
            new_name='user_story',
        ),
    ]
