# Generated by Django 5.1.4 on 2024-12-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_rename_user_comment_user_commenter_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user_comment_liker', 'comment'), name='unique_comment_like'),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('user_post_liker', 'post'), name='unique_post_like'),
        ),
    ]
