# Generated by Django 5.1.4 on 2024-12-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_post_description_en_post_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instagram.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instagram.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
